#ifndef __UPBCOMMON_H_
#define __UPBCOMMON_H_

/*
	Types of messages received through the XML_UPB__UPBNETWORKDATA property. These are
	messages from various devices on the network, or those generated by messages
	passed through the XML_UPB_UPBLINKDATA and reflected back to the appropriate
	modules.
	UPB_NETWORKDATA_DEVICEMESSAGE - A message generated by the device which a module
		represents.
	UPB_NETWORKDATA_BROADCAST - A message broadcast on the network to a Link ID.
	UPB_NETWORKDATA_DEVICERESPONSE - A message generated by the device which a module
		represents in response to a request.
	UPB_NETWORKDATA_ACCEPT - Acceptance of a message sent to the network which would
		not otherwise generate any type of response.
	UPB_NETWORKDATA_NAK - Rejection of a message sent to the network.
	UPB_NETWORKDATA_PIMREGISTERS - PIM register read response.
*/
#define UPB_NETWORKDATA_DEVICEMESSAGE 'M'
#define UPB_NETWORKDATA_BROADCAST 'C'
#define UPB_NETWORKDATA_DEVICERESPONSE 'S'
#define UPB_NETWORKDATA_ACCEPT 'A'
#define UPB_NETWORKDATA_NAK 'N'
#define UPB_NETWORKDATA_PIMREGISTERS 'R'

/*
	The specific destination type for the DID in a message for
	UPB_NETWORKDATA_DEVICEMESSAGE, UPB_NETWORKDATA_BROADCAST, and
	UPB_NETWORKDATA_DEVICERESPONSE messages.
	UPB_MESSAGE_TYPE_LINK - The destination ID represents a link.
	UPB_MESSAGE_TYPE_DIRECT - The destination ID represents a device.
*/
#define UPB_MESSAGE_TYPE_LINK 'L'
#define UPB_MESSAGE_TYPE_DIRECT 'D'

/*
	Prepended to a message sent to the network via XML_UPB__UPBNETWORKMESSAGE along
	with the MDID of the custom response to indicate that a response to this
	message is expected. This is used in cases where the message being sent is in
	some extended message set, so there would be no way of determining if a
	response from the device should be expected.
*/
#define UPB_MESSAGE_CUSTOM_RESPONSE 'R'
/*
	Prepended to a message sent to the network via XML_UPB__UPBNETWORKMESSAGE along
	with the MDID of SETREGISTERVALUES in order to update the local register cache
	only, and not send data to the corresponding device. This is used when the
	device is responding to a message that indicates registers have been already
	changed on the device.
*/
#define UPB_MESSAGE_CACHE_ONLY 'O'

/*
	The reserved device identifiers.
	BROADCAST_DEVICEID - Used to broadcast a message on a particular network.
	RESERVED1_DEVICEID - Reserved for future use.
	RESERVED2_DEVICEID - Reserved for future use.
	WRITEENABLED_DEVICEID - Represents all devices on a network whose registers are
		write enabled.
	SETUPMODE_DEVICEID - Represents all the devices on a network in setup mode.
	DEFAULT_DEVICEID - Represents the PC destination for messages.
*/
#define BROADCAST_DEVICEID 0x00
#define RESERVED1_DEVICEID 0xFB
#define RESERVED2_DEVICEID 0xFC
#define WRITEENABLED_DEVICEID 0xFD
#define SETUPMODE_DEVICEID 0xFE
#define DEFAULT_DEVICEID 0xFF

/*
	The reserved network identifiers.
	GLOBAL_NETWORKID - Used to broadcast to all networks.
	RESERVED1_NETWORKID - Reserved for future use.
	RESERVED2_NETWORKID - Reserved for future use.
	WRITEENABLED_NETWORKID - Broadcast to all devices on all networks whose registers
		are write enabled.
	SETUPMODE_NETWORKID - Broadcast to all devices on all networks in setup mode.
	DEFAULT_NETWORKID - The factory default network for some devices.
*/
#define GLOBAL_NETWORKID 0x00
#define RESERVED1_NETWORKID 0xFB
#define RESERVED2_NETWORKID 0xFC
#define WRITEENABLED_NETWORKID 0xFD
#define SETUPMODE_NETWORKID 0xFE
#define DEFAULT_NETWORKID 0xFF

/*
	Macros to manipulate message command identifiers.
	MAKE_MDID(set, cmd) - Create an MDID given a command set, and specific command
		within that set.
	SET_FROM_MDID(mdid) - Extract the command set from an MDID.
	CMD_FROM_MDID(mdid) - Extract the command from an MDID.
*/
#define MAKE_MDID(set, cmd) ((set) | (cmd))
#define SET_FROM_MDID(mdid) ((mdid) & 0xe0)
#define CMD_FROM_MDID(mdid) ((mdid) & 0x1f)

/*
	The command sets as described by UPB.
*/
#define MDID_CORE_COMMANDS 0x00
#define MDID_DEVICE_CONTROL_COMMANDS 0x20
#define MDID_RESERVED_COMMAND_SET1 0x40
#define MDID_RESERVED_COMMAND_SET2 0x60
#define MDID_CORE_REPORTS 0x80
#define MDID_RESERVED_REPORT_SET1 0xa0
#define MDID_RESERVED_REPORT_SET2 0xc0
#define MDID_EXTENDED_MESSAGE_SET 0xe0

/*
	VIRTUALIZED_MESSAGE_SET - The extended message command set used when virtualizing
		a device's transmit commands.
*/
#define VIRTUALIZED_MESSAGE_SET 0x02

/*
	The commands as described by UPB.
*/
#define MDID_CORE_COMMAND_NULL 0x00
#define MDID_CORE_COMMAND_WRITEENABLE 0x01
#define MDID_CORE_COMMAND_WRITEPROTECT 0x02
#define MDID_CORE_COMMAND_STARTSETUP 0x03
#define MDID_CORE_COMMAND_STOPSETUP 0x04
#define MDID_CORE_COMMAND_GETSETUPTIME 0x05
#define MDID_CORE_COMMAND_AUTOADDRESS 0x06
#define MDID_CORE_COMMAND_GETDEVICESTATUS 0x07
#define MDID_CORE_COMMAND_SETDEVICESTATUS 0x08
#define MDID_CORE_COMMAND_GETSIGNALSTRENGTH 0x09
#define MDID_CORE_COMMAND_GETNOISELEVEL 0x0A
#define MDID_CORE_COMMAND_ADDLINK 0x0B
#define MDID_CORE_COMMAND_DELETELINK 0x0C
#define MDID_CORE_COMMAND_TRANSMITMESSAGE 0x0D
#define MDID_CORE_COMMAND_RESETDEVICE 0x0E
#define MDID_CORE_COMMAND_GETDEVICESIGNATURE 0x0F
#define MDID_CORE_COMMAND_GETREGISTERVALUES 0x10
#define MDID_CORE_COMMAND_SETREGISTERVALUES 0x11

#define MDID_DEVICE_CONTROL_COMMAND_ACTIVATELINK 0x00
#define MDID_DEVICE_CONTROL_COMMAND_DEACTIVATELINK 0x01
#define MDID_DEVICE_CONTROL_COMMAND_GOTO 0x02
#define MDID_DEVICE_CONTROL_COMMAND_FADESTART 0x03
#define MDID_DEVICE_CONTROL_COMMAND_FADESTOP 0x04
#define MDID_DEVICE_CONTROL_COMMAND_BLINK 0x05
#define MDID_DEVICE_CONTROL_COMMAND_REPORTSTATE 0x10
#define MDID_DEVICE_CONTROL_COMMAND_STORESTATE 0x11

#define MDID_DEVICE_CORE_REPORT_SETUPTIME 0x05
#define MDID_DEVICE_CORE_REPORT_DEVICESTATE 0x06
#define MDID_DEVICE_CORE_REPORT_DEVICESTATUS 0x07
#define MDID_DEVICE_CORE_REPORT_SIGNALSTRENGTH 0x09
#define MDID_DEVICE_CORE_REPORT_NOISELEVEL 0x0a
#define MDID_DEVICE_CORE_REPORT_DEVICESIGNATURE 0x0f
#define MDID_DEVICE_CORE_REPORT_REGISTERVALUES 0x10
#define MDID_DEVICE_CORE_REPORT_RAMVALUES 0x11
#define MDID_DEVICE_CORE_REPORT_RAWDATA 0x12
#define MDID_DEVICE_CORE_REPORT_HEARTBEAT 0x13
#define MDID_DEVICE_CORE_REPORT_ACK 0x14

/*
	UPB_MODULE_REGISTERS - The total number of registers available on a device.
	UPB_MODULE_MAXREGISTERIO - The maximum number of registers that can be read in a
		single request.
*/
#define UPB_MODULE_REGISTERS 256
#define UPB_MODULE_MAXREGISTERIO 16

#define UPB_SWITCH_FADERATE_SNAP 0
#define UPB_SWITCH_FADERATE_POINT8SECONDS 1
#define UPB_SWITCH_FADERATE_1POINT6SECONDS 2
#define UPB_SWITCH_FADERATE_3POINT3SECONDS 3
#define UPB_SWITCH_FADERATE_5SECONDS 4
#define UPB_SWITCH_FADERATE_6POINT6SECONDS 5
#define UPB_SWITCH_FADERATE_10SECONDS 6
#define UPB_SWITCH_FADERATE_20SECONDS 7
#define UPB_SWITCH_FADERATE_30SECONDS 8
#define UPB_SWITCH_FADERATE_1MINUTE 9
#define UPB_SWITCH_FADERATE_2MINUTES 10
#define UPB_SWITCH_FADERATE_5MINUTES 11
#define UPB_SWITCH_FADERATE_10MINUTES 12
#define UPB_SWITCH_FADERATE_15MINUTES 13
#define UPB_SWITCH_FADERATE_30MINUTES 14
#define UPB_SWITCH_FADERATE_1HOUR 15
#define UPB_SWITCH_FADERATE_DEFAULT 255

#define UPB_SWITCH_LASTONLEVEL 255

#define UPB_LASTLINKID 0

#define SYS_BUTTON_STATE_RELEASE 0
#define SYS_BUTTON_STATE_PRESS 1
#define SYS_BUTTON_STATE_HOLD 2
#define SYS_BUTTON_STATE_DOUBLETAP 3

/*
	XML_SYS_PATH_SEPARATOR - Path element separator.
	XML_SYS_DEVICES_ROOT - Root of devices tree.
	XML_SYS_NAME - Premise standard name property.
	XML_UPB_ROOT - Root of UPB devices tree.
	XML_UPB_SCHEMA_ROOT - Root of UPB schema tree.
	XML_UPB_UPBINTERFACE - UPB Interface class name.
	XML_UPB_PIM - UPB PIM class name.
	XML_UPB_MODULE - UPB Module class name.
	XML_UPB_RECEIVECOMPONENT - Receive Component class name.
	XML_UPB_NETWORKID - Network ID property name.
	XML_UPB_MODULEID - Module ID property name.
	XML_UPB_UPBDEVICEINITIALIZED - Device Initialized property name.
	XML_UPB_UPBLINKDATA - Link Data property name.
	XML_UPB__UPBNETWORKDATA - Network Data property name.
	XML_UPB__SETUPREGISTERCACHE - Register Cache property name.
	XML_UPB__UPBNETWORKMESSAGE - Network Message property name.
	XML_UPB_LINKID - Link ID property name.
	XML_UPB_VIRTUALIZE - Virtualize property name.
	XML_UPB__UPBNETWORKIDLE - Network Idle property name.
*/
#define XML_SYS_PATH_SEPARATOR L"/"
#define XML_SYS_DEVICES_ROOT L"sys://Devices"
#define XML_SYS_NAME L"Name"
#define XML_SYS_BUTTONSTATE L"ButtonState"
#define XML_SYS_STATUS L"Status"
#define XML_SYS_BRIGHTNESS L"Brightness"
#define XML_SYS_POWERSTATE L"PowerState"
#define XML_SYS_TRIGGER L"Trigger"
#define XML_SYS_PRESETDIM L"PresetDim"

#define XML_UPB_ROOT XML_SYS_DEVICES_ROOT XML_SYS_PATH_SEPARATOR L"upb"
#define XML_UPB_SCHEMA_ROOT L"sys://Schema" XML_SYS_PATH_SEPARATOR L"upb"
#define XML_UPB_UPBINTERFACE L"upbInterface"
#define XML_UPB_PIM L"upbPIM"
#define XML_UPB_MODULE L"upbModule"
#define XML_UPB_RECEIVECOMPONENT L"ReceiveComponent"
#define XML_UPB_SWITCHRECEIVECOMPONENT L"SwitchReceiveComponent"
#define XML_UPB_SWITCHRECEIVECOMPONENTS L"SwitchReceiveComponents"
#define XML_UPB_TRANSMITCOMPONENT L"TransmitComponent"
#define XML_UPB_COMPONENTID L"ComponentID"
#define XML_UPB_LIGHTLEVEL L"LightLevel"
#define XML_UPB_LASTONLEVEL L"LastOnLevel"
#define XML_UPB_DEFAULTFADERATE L"DefaultFadeRate"
#define XML_UPB_FADERATE L"FadeRate"
#define XML_UPB_TRANSMITCOMMANDS L"TransmitCommands"
#define XML_UPB_TRANSMITCOMMAND L"TransmitCommand"
#define XML_UPB_COMMANDID L"CommandID"
#define XML_UPB_COMMAND L"Command"
#define XML_UPB_EVENTPACKETTYPE L"EventPacketType"
#define XML_UPB_ACKMESSAGEREQUEST L"AckMessageRequest"
#define XML_UPB_IDPULSEREQUEST L"IdPulseRequest"
#define XML_UPB_ACKPULSEREQUEST L"AckPulseRequest"
#define XML_UPB_TRANSMISSIONCOUNT L"TransmissionCount"
#define XML_UPB_NETWORKID L"NetworkID"
#define XML_UPB_MODULEID L"ModuleID"
#define XML_UPB_UPBDEVICEINITIALIZED L"upbDeviceInitialized"
#define XML_UPB_UPBLINKDATA L"upbLinkData"
#define XML_UPB_SETUPREGISTERCACHE L"SetupRegisterCache"
#define XML_UPB_UPBNETWORKMESSAGE L"upbNetworkMessage"
#define XML_UPB_UPBNETWORKDATA L"upbNetworkData"
#define XML_UPB_LINKID L"LinkID"
#define XML_UPB_VIRTUALIZE L"Virtualize"
#define XML_UPB_UPBNETWORKIDLE L"upbNetworkIdle"
#define XML_UPB_MANUFACTURERID L"ManufacturerID"
#define XML_UPB_PRODUCTID L"ProductID"
#define XML_UPB_UPBFIRMWAREVERSION L"upbFirmwareVersion"
#define XML_UPB_LEDMODE L"LEDMode"
#define XML_UPB_LEDONCOLOR L"LEDOnColor"
#define XML_UPB_LEDOFFCOLOR L"LEDOffColor"

#endif //__UPBCOMMON_H_
